### ISSUE TITLE
Add OCR parsing example 

### ISSUE THREAD

**Issue by jlandure** [hgwood/hash-code-parser#5]
Example:
ID CARD http://ocrsdk.com/images/doc/foreignpassportrus.jpg
input: `P<RUSMALBOLSKYI<<KOVBOJ`
output: 

``` json
{
  "country": "RUS",
  "name": "MALBOLSKYI",
  "firstname": "KOVBOJ"
}
```

**Comment by hgwood** [comment]
Quite a departure from Hash Code inputs, but I'll give it a try. :)

**Comment by hgwood** [comment]
I decided to optimize for Hash Code problem inputs.
