### ISSUE TITLE
Rename the lib and publish on npmjs.org

### ISSUE THREAD

**Issue by jlandure** [hgwood/hash-code-parser#8]
Call it 
- simple-parser
- data-to-json-parser
- js-parser-json
- js-pars-on
- jsparsec (inspired from jparsec)

**Comment by hgwood** [comment]
Not sure I want to make this a general parser combinator. [There are already plenty of these](http://stackoverflow.com/questions/14526904/current-state-of-javascript-parser-combinators). I need to think about where I want this project to go.

**Comment by hgwood** [comment]
I decided to optimize the syntax for Hash Code problem inputs. The module is now published on npm as [jolicitron](https://www.npmjs.com/package/jolicitron).
